## Getting Data from GitHub

In [ ]:
!git clone https://github.com/YafetPontoh/data_bank.git

fatal: destination path 'data_bank' already exists and is not an empty directory.

## Import Library

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

## Gathering All Data

In [ ]:
df = pd.read_csv("data_bank/training_dataset.csv")
df.head()

,customer_number,usia,pekerjaan,status_perkawinan,pendidikan,gagal_bayar_sebelumnya,pinjaman_rumah,pinjaman_pribadi,jenis_kontak,bulan_kontak_terakhir,...,hari_sejak_kontak_sebelumnya,jumlah_kontak_sebelumnya,hasil_kampanye_sebelumnya,tingkat_variasi_pekerjaan,indeks_harga_konsumen,indeks_kepercayaan_konsumen,suku_bunga_euribor_3bln,jumlah_pekerja,pulau,berlangganan_deposito
0,531036,63,sosial media specialis,menikah,Pendidikan Tinggi,no,yes,no,cellular,jul,...,999,0,nonexistent,-1.7,94.215,-40.3,0.885,4991.6,Papua,1
1,999241,43,teknisi,menikah,Pendidikan Tinggi,no,yes,no,cellular,nov,...,999,0,nonexistent,-0.1,93.200,-42.0,4.021,5195.8,Sulawesi,0
2,995002,29,sosial media specialis,lajang,Pendidikan Tinggi,no,yes,yes,cellular,jul,...,999,0,nonexistent,1.4,93.918,-42.7,4.958,5228.1,Papua,0
3,932750,40,pekerja kasar,menikah,SMA,no,no,no,telephone,may,...,999,0,nonexistent,1.1,93.994,-36.4,4.859,5191.0,Sumatera,1
4,684699,40,sosial media specialis,lajang,Pendidikan Tinggi,no,no,no,cellular,aug,...,999,0,nonexistent,1.4,93.444,-36.1,4.964,5228.1,Bali,0

In [ ]:
df_val = pd.read_csv("data_bank/validation_set.csv")
df_val.head()

,customer_number,usia,pekerjaan,status_perkawinan,pendidikan,gagal_bayar_sebelumnya,pinjaman_rumah,pinjaman_pribadi,jenis_kontak,bulan_kontak_terakhir,...,jumlah_kontak_kampanye_ini,hari_sejak_kontak_sebelumnya,jumlah_kontak_sebelumnya,hasil_kampanye_sebelumnya,tingkat_variasi_pekerjaan,indeks_harga_konsumen,indeks_kepercayaan_konsumen,suku_bunga_euribor_3bln,jumlah_pekerja,pulau
0,445420,35,penyedia jasa,menikah,SMA,no,yes,yes,cellular,jul,...,1,999,0,nonexistent,1.4,93.918,-42.7,4.960,5228.1,Jawa
1,585604,52,teknisi,lajang,Diploma,unknown,no,no,telephone,may,...,4,999,0,nonexistent,1.1,93.994,-36.4,4.860,5191.0,Papua
2,888824,37,pekerja kasar,menikah,SMP,unknown,yes,no,telephone,may,...,3,999,0,nonexistent,1.1,93.994,-36.4,4.856,5191.0,Bali
3,816820,51,pengangguran,menikah,Diploma,no,no,no,telephone,may,...,3,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,Sumatera
4,542716,45,teknisi,cerai,SMA,no,yes,no,cellular,may,...,1,999,1,failure,-1.8,92.893,-46.2,1.327,5099.1,Sumatera

In [ ]:
dataset = [df, df_val]

# Check info in dataset
for i in dataset:
  print(i.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22916 entries, 0 to 22915
Data columns (total 22 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   customer_number               22916 non-null  int64
 1   usia                          22916 non-null  int64
 2   pekerjaan                     22916 non-null  object
 3   status_perkawinan             22916 non-null  object
 4   pendidikan                    22916 non-null  object
 5   gagal_bayar_sebelumnya        22916 non-null  object
 6   pinjaman_rumah                22916 non-null  object
 7   pinjaman_pribadi              22916 non-null  object
 8   jenis_kontak                  22916 non-null  object
 9   bulan_kontak_terakhir         22916 non-null  object
 10  hari_kontak_terakhir          22916 non-null  object
 11  jumlah_kontak_kampanye_ini    22916 non-null  int64
 12  hari_sejak_kontak_sebelumnya  22916 non-null  int64
 13  jumlah_kontak_sebelumnya      22916 non-null  int64
 14  hasil_kampanye_sebelumnya     22916 non-null  object
 15  tingkat_variasi_pekerjaan     22916 non-null  float64
 16  indeks_harga_konsumen         22916 non-null  float64
 17  indeks_kepercayaan_konsumen   22916 non-null  float64
 18  suku_bunga_euribor_3bln       22916 non-null  float64
 19  jumlah_pekerja                22916 non-null  float64
 20  pulau                         22916 non-null  object
 21  berlangganan_deposito         22916 non-null  int64
dtypes: float64(5), int64(6), object(11)
memory usage: 3.8+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5729 entries, 0 to 5728
Data columns (total 21 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   customer_number               5729 non-null   int64
 1   usia                          5729 non-null   int64
 2   pekerjaan                     5729 non-null   object
 3   status_perkawinan             5729 non-null   object
 4   pendidikan                    5729 non-null   object
 5   gagal_bayar_sebelumnya        5729 non-null   object
 6   pinjaman_rumah                5729 non-null   object
 7   pinjaman_pribadi              5729 non-null   object
 8   jenis_kontak                  5729 non-null   object
 9   bulan_kontak_terakhir         5729 non-null   object
 10  hari_kontak_terakhir          5729 non-null   object
 11  jumlah_kontak_kampanye_ini    5729 non-null   int64
 12  hari_sejak_kontak_sebelumnya  5729 non-null   int64
 13  jumlah_kontak_sebelumnya      5729 non-null   int64
 14  hasil_kampanye_sebelumnya     5729 non-null   object
 15  tingkat_variasi_pekerjaan     5729 non-null   float64
 16  indeks_harga_konsumen         5729 non-null   float64
 17  indeks_kepercayaan_konsumen   5729 non-null   float64
 18  suku_bunga_euribor_3bln       5729 non-null   float64
 19  jumlah_pekerja                5729 non-null   float64
 20  pulau                         5729 non-null   object
dtypes: float64(5), int64(5), object(11)
memory usage: 940.0+ KB
None

## Data Training

In [ ]:
df_clean = df.copy()
df_clean = df.replace("unknown", np.nan)
# df_clean = df.replace("nonexistent", np.NaN)
df_clean.dropna(inplace=True)
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16948 entries, 0 to 22913
Data columns (total 22 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   customer_number               16948 non-null  int64
 1   usia                          16948 non-null  int64
 2   pekerjaan                     16948 non-null  object
 3   status_perkawinan             16948 non-null  object
 4   pendidikan                    16948 non-null  object
 5   gagal_bayar_sebelumnya        16948 non-null  object
 6   pinjaman_rumah                16948 non-null  object
 7   pinjaman_pribadi              16948 non-null  object
 8   jenis_kontak                  16948 non-null  object
 9   bulan_kontak_terakhir         16948 non-null  object
 10  hari_kontak_terakhir          16948 non-null  object
 11  jumlah_kontak_kampanye_ini    16948 non-null  int64
 12  hari_sejak_kontak_sebelumnya  16948 non-null  int64
 13  jumlah_kontak_sebelumnya      16948 non-null  int64
 14  hasil_kampanye_sebelumnya     16948 non-null  object
 15  tingkat_variasi_pekerjaan     16948 non-null  float64
 16  indeks_harga_konsumen         16948 non-null  float64
 17  indeks_kepercayaan_konsumen   16948 non-null  float64
 18  suku_bunga_euribor_3bln       16948 non-null  float64
 19  jumlah_pekerja                16948 non-null  float64
 20  pulau                         16948 non-null  object
 21  berlangganan_deposito         16948 non-null  int64
dtypes: float64(5), int64(6), object(11)
memory usage: 3.0+ MB

In [ ]:
outliers = df_clean[df_clean["hari_sejak_kontak_sebelumnya"] == 999]
outliers.head()

,customer_number,usia,pekerjaan,status_perkawinan,pendidikan,gagal_bayar_sebelumnya,pinjaman_rumah,pinjaman_pribadi,jenis_kontak,bulan_kontak_terakhir,...,hari_sejak_kontak_sebelumnya,jumlah_kontak_sebelumnya,hasil_kampanye_sebelumnya,tingkat_variasi_pekerjaan,indeks_harga_konsumen,indeks_kepercayaan_konsumen,suku_bunga_euribor_3bln,jumlah_pekerja,pulau,berlangganan_deposito
0,531036,63,sosial media specialis,menikah,Pendidikan Tinggi,no,yes,no,cellular,jul,...,999,0,nonexistent,-1.7,94.215,-40.3,0.885,4991.6,Papua,1
1,999241,43,teknisi,menikah,Pendidikan Tinggi,no,yes,no,cellular,nov,...,999,0,nonexistent,-0.1,93.200,-42.0,4.021,5195.8,Sulawesi,0
2,995002,29,sosial media specialis,lajang,Pendidikan Tinggi,no,yes,yes,cellular,jul,...,999,0,nonexistent,1.4,93.918,-42.7,4.958,5228.1,Papua,0
3,932750,40,pekerja kasar,menikah,SMA,no,no,no,telephone,may,...,999,0,nonexistent,1.1,93.994,-36.4,4.859,5191.0,Sumatera,1
4,684699,40,sosial media specialis,lajang,Pendidikan Tinggi,no,no,no,cellular,aug,...,999,0,nonexistent,1.4,93.444,-36.1,4.964,5228.1,Bali,0

In [ ]:
d_duplikat = df_clean.duplicated(subset = "customer_number").sum()
d_duplikat

np.int64(0)

In [ ]:
df_clean.drop(columns="customer_number", inplace=True)

In [ ]:
df_clean.columns

Index(['usia', 'pekerjaan', 'status_perkawinan', 'pendidikan',
       'gagal_bayar_sebelumnya', 'pinjaman_rumah', 'pinjaman_pribadi',
       'jenis_kontak', 'bulan_kontak_terakhir', 'hari_kontak_terakhir',
       'jumlah_kontak_kampanye_ini', 'hari_sejak_kontak_sebelumnya',
       'jumlah_kontak_sebelumnya', 'hasil_kampanye_sebelumnya',
       'tingkat_variasi_pekerjaan', 'indeks_harga_konsumen',
       'indeks_kepercayaan_konsumen', 'suku_bunga_euribor_3bln',
       'jumlah_pekerja', 'pulau', 'berlangganan_deposito'],
      dtype='object')

In [ ]:
binary = {'yes':1, 'no':0}
binary_col =['gagal_bayar_sebelumnya', 'pinjaman_rumah',
       'pinjaman_pribadi']
df_clean[binary_col] = df_clean[binary_col].replace(binary).astype(object)

<ipython-input-11-5ad67f52cd66>:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_clean[binary_col] = df_clean[binary_col].replace(binary).astype(object)

In [ ]:
df_clean = df_clean.apply(lambda x: x.astype(float) if x.dtype=="int64" else x)
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16948 entries, 0 to 22913
Data columns (total 21 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   usia                          16948 non-null  float64
 1   pekerjaan                     16948 non-null  object
 2   status_perkawinan             16948 non-null  object
 3   pendidikan                    16948 non-null  object
 4   gagal_bayar_sebelumnya        16948 non-null  object
 5   pinjaman_rumah                16948 non-null  object
 6   pinjaman_pribadi              16948 non-null  object
 7   jenis_kontak                  16948 non-null  object
 8   bulan_kontak_terakhir         16948 non-null  object
 9   hari_kontak_terakhir          16948 non-null  object
 10  jumlah_kontak_kampanye_ini    16948 non-null  float64
 11  hari_sejak_kontak_sebelumnya  16948 non-null  float64
 12  jumlah_kontak_sebelumnya      16948 non-null  float64
 13  hasil_kampanye_sebelumnya     16948 non-null  object
 14  tingkat_variasi_pekerjaan     16948 non-null  float64
 15  indeks_harga_konsumen         16948 non-null  float64
 16  indeks_kepercayaan_konsumen   16948 non-null  float64
 17  suku_bunga_euribor_3bln       16948 non-null  float64
 18  jumlah_pekerja                16948 non-null  float64
 19  pulau                         16948 non-null  object
 20  berlangganan_deposito         16948 non-null  float64
dtypes: float64(10), object(11)
memory usage: 2.8+ MB

In [ ]:
category = df_clean.select_dtypes(include=['object']).columns

In [ ]:
df_enc = df_clean.copy()

In [ ]:
df_enc = pd.get_dummies(df_enc, columns=category, drop_first=True)
df_enc.head()

,usia,jumlah_kontak_kampanye_ini,hari_sejak_kontak_sebelumnya,jumlah_kontak_sebelumnya,tingkat_variasi_pekerjaan,indeks_harga_konsumen,indeks_kepercayaan_konsumen,suku_bunga_euribor_3bln,jumlah_pekerja,berlangganan_deposito,...,hari_kontak_terakhir_wed,hasil_kampanye_sebelumnya_nonexistent,hasil_kampanye_sebelumnya_success,pulau_Jawa,pulau_Kalimantan,pulau_NTB,pulau_NTT,pulau_Papua,pulau_Sulawesi,pulau_Sumatera
0,63.0,2.0,999.0,0.0,-1.7,94.215,-40.3,0.885,4991.6,1.0,...,False,True,False,False,False,False,False,True,False,False
1,43.0,2.0,999.0,0.0,-0.1,93.200,-42.0,4.021,5195.8,0.0,...,False,True,False,False,False,False,False,False,True,False
2,29.0,1.0,999.0,0.0,1.4,93.918,-42.7,4.958,5228.1,0.0,...,False,True,False,False,False,False,False,True,False,False
3,40.0,2.0,999.0,0.0,1.1,93.994,-36.4,4.859,5191.0,1.0,...,True,True,False,False,False,False,False,False,False,True
4,40.0,3.0,999.0,0.0,1.4,93.444,-36.1,4.964,5228.1,0.0,...,True,True,False,False,False,False,False,False,False,False

In [ ]:
df_enc['pernah_dikontak_sebelumnya'] = (df_enc['jumlah_kontak_sebelumnya'] > 0).astype(float)
df_enc['lama_tidak_dikontak'] = (df_enc['hari_sejak_kontak_sebelumnya'] != 999).astype(float)

In [ ]:
df_enc.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16948 entries, 0 to 22913
Data columns (total 56 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   usia                                   16948 non-null  float64
 1   jumlah_kontak_kampanye_ini             16948 non-null  float64
 2   hari_sejak_kontak_sebelumnya           16948 non-null  float64
 3   jumlah_kontak_sebelumnya               16948 non-null  float64
 4   tingkat_variasi_pekerjaan              16948 non-null  float64
 5   indeks_harga_konsumen                  16948 non-null  float64
 6   indeks_kepercayaan_konsumen            16948 non-null  float64
 7   suku_bunga_euribor_3bln                16948 non-null  float64
 8   jumlah_pekerja                         16948 non-null  float64
 9   berlangganan_deposito                  16948 non-null  float64
 10  pekerjaan_entrepreneur                 16948 non-null  bool
 11  pekerjaan_mahasiswa                    16948 non-null  bool
 12  pekerjaan_manajer                      16948 non-null  bool
 13  pekerjaan_pekerja kasar                16948 non-null  bool
 14  pekerjaan_pemilik bisnis               16948 non-null  bool
 15  pekerjaan_pengangguran                 16948 non-null  bool
 16  pekerjaan_pensiunan                    16948 non-null  bool
 17  pekerjaan_penyedia jasa                16948 non-null  bool
 18  pekerjaan_sosial media specialis       16948 non-null  bool
 19  pekerjaan_teknisi                      16948 non-null  bool
 20  status_perkawinan_lajang               16948 non-null  bool
 21  status_perkawinan_menikah              16948 non-null  bool
 22  pendidikan_Pendidikan Tinggi           16948 non-null  bool
 23  pendidikan_SD                          16948 non-null  bool
 24  pendidikan_SMA                         16948 non-null  bool
 25  pendidikan_SMP                         16948 non-null  bool
 26  pendidikan_TIDAK SEKOLAH               16948 non-null  bool
 27  pendidikan_Tidak Tamat SD              16948 non-null  bool
 28  gagal_bayar_sebelumnya_1               16948 non-null  bool
 29  pinjaman_rumah_1                       16948 non-null  bool
 30  pinjaman_pribadi_1                     16948 non-null  bool
 31  jenis_kontak_telephone                 16948 non-null  bool
 32  bulan_kontak_terakhir_aug              16948 non-null  bool
 33  bulan_kontak_terakhir_dec              16948 non-null  bool
 34  bulan_kontak_terakhir_jul              16948 non-null  bool
 35  bulan_kontak_terakhir_jun              16948 non-null  bool
 36  bulan_kontak_terakhir_mar              16948 non-null  bool
 37  bulan_kontak_terakhir_may              16948 non-null  bool
 38  bulan_kontak_terakhir_nov              16948 non-null  bool
 39  bulan_kontak_terakhir_oct              16948 non-null  bool
 40  bulan_kontak_terakhir_sep              16948 non-null  bool
 41  hari_kontak_terakhir_mon               16948 non-null  bool
 42  hari_kontak_terakhir_thu               16948 non-null  bool
 43  hari_kontak_terakhir_tue               16948 non-null  bool
 44  hari_kontak_terakhir_wed               16948 non-null  bool
 45  hasil_kampanye_sebelumnya_nonexistent  16948 non-null  bool
 46  hasil_kampanye_sebelumnya_success      16948 non-null  bool
 47  pulau_Jawa                             16948 non-null  bool
 48  pulau_Kalimantan                       16948 non-null  bool
 49  pulau_NTB                              16948 non-null  bool
 50  pulau_NTT                              16948 non-null  bool
 51  pulau_Papua                            16948 non-null  bool
 52  pulau_Sulawesi                         16948 non-null  bool
 53  pulau_Sumatera                         16948 non-null  bool
 54  pernah_dikontak_sebelumnya             16948 non-null  float64
 55  lama_tidak_dikontak                    16948 non-null  float64
dtypes: bool(44), float64(12)
memory usage: 2.4 MB

In [ ]:
pd.options.display.float_format = '{:}'.format

In [ ]:
df_enc.nunique()

usia                                      75
jumlah_kontak_kampanye_ini                40
hari_sejak_kontak_sebelumnya              24
jumlah_kontak_sebelumnya                   8
tingkat_variasi_pekerjaan                 10
indeks_harga_konsumen                     26
indeks_kepercayaan_konsumen               26
suku_bunga_euribor_3bln                  304
jumlah_pekerja                            11
berlangganan_deposito                      2
pekerjaan_entrepreneur                     2
pekerjaan_mahasiswa                        2
pekerjaan_manajer                          2
pekerjaan_pekerja kasar                    2
pekerjaan_pemilik bisnis                   2
pekerjaan_pengangguran                     2
pekerjaan_pensiunan                        2
pekerjaan_penyedia jasa                    2
pekerjaan_sosial media specialis           2
pekerjaan_teknisi                          2
status_perkawinan_lajang                   2
status_perkawinan_menikah                  2
pendidikan_Pendidikan Tinggi               2
pendidikan_SD                              2
pendidikan_SMA                             2
pendidikan_SMP                             2
pendidikan_TIDAK SEKOLAH                   2
pendidikan_Tidak Tamat SD                  2
gagal_bayar_sebelumnya_1                   2
pinjaman_rumah_1                           2
pinjaman_pribadi_1                         2
jenis_kontak_telephone                     2
bulan_kontak_terakhir_aug                  2
bulan_kontak_terakhir_dec                  2
bulan_kontak_terakhir_jul                  2
bulan_kontak_terakhir_jun                  2
bulan_kontak_terakhir_mar                  2
bulan_kontak_terakhir_may                  2
bulan_kontak_terakhir_nov                  2
bulan_kontak_terakhir_oct                  2
bulan_kontak_terakhir_sep                  2
hari_kontak_terakhir_mon                   2
hari_kontak_terakhir_thu                   2
hari_kontak_terakhir_tue                   2
hari_kontak_terakhir_wed                   2
hasil_kampanye_sebelumnya_nonexistent      2
hasil_kampanye_sebelumnya_success          2
pulau_Jawa                                 2
pulau_Kalimantan                           2
pulau_NTB                                  2
pulau_NTT                                  2
pulau_Papua                                2
pulau_Sulawesi                             2
pulau_Sumatera                             2
pernah_dikontak_sebelumnya                 2
lama_tidak_dikontak                        2
dtype: int64

## Testing Data Training

In [ ]:
X = df_enc.drop(columns="berlangganan_deposito")
y = df_enc["berlangganan_deposito"]

In [ ]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16948 entries, 0 to 22913
Data columns (total 55 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   usia                                   16948 non-null  float64
 1   jumlah_kontak_kampanye_ini             16948 non-null  float64
 2   hari_sejak_kontak_sebelumnya           16948 non-null  float64
 3   jumlah_kontak_sebelumnya               16948 non-null  float64
 4   tingkat_variasi_pekerjaan              16948 non-null  float64
 5   indeks_harga_konsumen                  16948 non-null  float64
 6   indeks_kepercayaan_konsumen            16948 non-null  float64
 7   suku_bunga_euribor_3bln                16948 non-null  float64
 8   jumlah_pekerja                         16948 non-null  float64
 9   pekerjaan_entrepreneur                 16948 non-null  bool
 10  pekerjaan_mahasiswa                    16948 non-null  bool
 11  pekerjaan_manajer                      16948 non-null  bool
 12  pekerjaan_pekerja kasar                16948 non-null  bool
 13  pekerjaan_pemilik bisnis               16948 non-null  bool
 14  pekerjaan_pengangguran                 16948 non-null  bool
 15  pekerjaan_pensiunan                    16948 non-null  bool
 16  pekerjaan_penyedia jasa                16948 non-null  bool
 17  pekerjaan_sosial media specialis       16948 non-null  bool
 18  pekerjaan_teknisi                      16948 non-null  bool
 19  status_perkawinan_lajang               16948 non-null  bool
 20  status_perkawinan_menikah              16948 non-null  bool
 21  pendidikan_Pendidikan Tinggi           16948 non-null  bool
 22  pendidikan_SD                          16948 non-null  bool
 23  pendidikan_SMA                         16948 non-null  bool
 24  pendidikan_SMP                         16948 non-null  bool
 25  pendidikan_TIDAK SEKOLAH               16948 non-null  bool
 26  pendidikan_Tidak Tamat SD              16948 non-null  bool
 27  gagal_bayar_sebelumnya_1               16948 non-null  bool
 28  pinjaman_rumah_1                       16948 non-null  bool
 29  pinjaman_pribadi_1                     16948 non-null  bool
 30  jenis_kontak_telephone                 16948 non-null  bool
 31  bulan_kontak_terakhir_aug              16948 non-null  bool
 32  bulan_kontak_terakhir_dec              16948 non-null  bool
 33  bulan_kontak_terakhir_jul              16948 non-null  bool
 34  bulan_kontak_terakhir_jun              16948 non-null  bool
 35  bulan_kontak_terakhir_mar              16948 non-null  bool
 36  bulan_kontak_terakhir_may              16948 non-null  bool
 37  bulan_kontak_terakhir_nov              16948 non-null  bool
 38  bulan_kontak_terakhir_oct              16948 non-null  bool
 39  bulan_kontak_terakhir_sep              16948 non-null  bool
 40  hari_kontak_terakhir_mon               16948 non-null  bool
 41  hari_kontak_terakhir_thu               16948 non-null  bool
 42  hari_kontak_terakhir_tue               16948 non-null  bool
 43  hari_kontak_terakhir_wed               16948 non-null  bool
 44  hasil_kampanye_sebelumnya_nonexistent  16948 non-null  bool
 45  hasil_kampanye_sebelumnya_success      16948 non-null  bool
 46  pulau_Jawa                             16948 non-null  bool
 47  pulau_Kalimantan                       16948 non-null  bool
 48  pulau_NTB                              16948 non-null  bool
 49  pulau_NTT                              16948 non-null  bool
 50  pulau_Papua                            16948 non-null  bool
 51  pulau_Sulawesi                         16948 non-null  bool
 52  pulau_Sumatera                         16948 non-null  bool
 53  pernah_dikontak_sebelumnya             16948 non-null  float64
 54  lama_tidak_dikontak                    16948 non-null  float64
dtypes: bool(44), float64(11)
memory usage: 2.3 MB

In [ ]:
numeric_col = X.select_dtypes(include=["float64"]).columns
scaler = StandardScaler()
X[numeric_col] = scaler.fit_transform(X[numeric_col])

In [ ]:
X.head()

,usia,jumlah_kontak_kampanye_ini,hari_sejak_kontak_sebelumnya,jumlah_kontak_sebelumnya,tingkat_variasi_pekerjaan,indeks_harga_konsumen,indeks_kepercayaan_konsumen,suku_bunga_euribor_3bln,jumlah_pekerja,pekerjaan_entrepreneur,...,hasil_kampanye_sebelumnya_success,pulau_Jawa,pulau_Kalimantan,pulau_NTB,pulau_NTT,pulau_Papua,pulau_Sulawesi,pulau_Sumatera,pernah_dikontak_sebelumnya,lama_tidak_dikontak
0,2.3127666635470576,-0.19090936056274374,0.21306759293198435,-0.3687172049903771,-1.0034727243741155,1.1735693052430056,0.06000474250910418,-1.4426590824599035,-2.2442475677824967,False,...,False,False,False,False,False,True,False,False,-0.420939060075216,-0.21306916780458074
1,0.38370160323195784,-0.19090936056274374,0.21306759293198435,-0.3687172049903771,-0.013759801012920788,-0.5516820239508127,-0.2938871430381079,0.31817106513823656,0.4692813154268964,False,...,False,False,False,False,False,False,True,False,-0.420939060075216,-0.21306916780458074
2,-0.9666439389886119,-0.5515348446039142,0.21306759293198435,-0.3687172049903771,0.9140960646381993,0.6687420690158543,-0.4396073312046074,0.8442864504378086,0.898502583437004,False,...,False,False,False,False,False,True,False,False,-0.420939060075216,-0.21306916780458074
3,0.09434184418469292,-0.19090936056274374,0.21306759293198435,-0.3687172049903771,0.7285248915079753,0.7979234493298629,0.8718743622938833,0.7886990191201375,0.40549611151207954,False,...,False,False,False,False,False,False,False,True,-0.420939060075216,-0.21306916780458074
4,0.09434184418469292,0.1697161234784267,0.21306759293198435,-0.3687172049903771,0.9140960646381993,-0.13694180294264413,0.9343258715080964,0.8476553856691826,0.898502583437004,False,...,False,False,False,False,False,False,False,False,-0.420939060075216,-0.21306916780458074

In [ ]:
y.head()

0   1.0
1   0.0
2   0.0
3   1.0
4   0.0
Name: berlangganan_deposito, dtype: float64

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=42)

In [ ]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((13558, 55), (3390, 55), (13558,), (3390,))

In [ ]:
model = Sequential([
    Dense(32,  activation="relu", input_shape=(X_train.shape[1],)),
    Dense(16, activation="relu"),
    Dense(1, activation="sigmoid")
])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
model.compile(optimizer=Adam(learning_rate=0.001), loss="binary_crossentropy", metrics=["accuracy"])

In [ ]:
history = model.fit(X_train, y_train, epochs= 50, batch_size = 32, validation_data = (X_test, y_test), verbose=0)

In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │         1,792 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 7,013 (27.40 KB)

 Trainable params: 2,337 (9.13 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 4,676 (18.27 KB)

In [ ]:
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test Accuracy : {accuracy:.4f}")

106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8786 - loss: 0.3457
Test Accuracy : 0.8714

## Data Validation

In [ ]:
def preprocessing_data(data):
    data_clean = data.copy()
    data_clean = data.replace("unknown", np.nan)
    data_clean.dropna(inplace=True)
    # Drop Duplicated berdasarkan customer_numbernya
    data_clean.drop_duplicates(subset="customer_number", inplace=True)
    # Drop kolom customer_number
    data_clean.drop(columns="customer_number", inplace=True)
    binary = {'yes':1, 'no':0}
    binary_col =['gagal_bayar_sebelumnya', 'pinjaman_rumah',
       'pinjaman_pribadi']
    data_clean[binary_col] = data_clean[binary_col].replace(binary).astype(object)
    data_clean = data_clean.apply(lambda x: x.astype(float) if x.dtype=="int64" else x)
    category = data_clean.select_dtypes(include=['object']).columns
    data_enc = data_clean.copy()
    data_enc = pd.get_dummies(data_enc, columns=category, drop_first=True)
    data_enc["pernah_dikontak_sebelumnya"] = (data_enc["jumlah_kontak_sebelumnya"] > 0).astype(float)
    data_enc["lama_tidak_dikontak"] = (data_enc["hari_sejak_kontak_sebelumnya"] != 999).astype(float)
    pd.options.display.float_format = '{:}'.format
    y_val = data_enc.copy()
    numeric_col = y_val.select_dtypes(include=["float64"]).columns
    scaler = StandardScaler()
    y_val[numeric_col] = scaler.fit_transform(y_val[numeric_col])
    return y_val

In [ ]:
val_processed = preprocessing_data(df_val)

<ipython-input-32-4dd49eae086d>:12: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data_clean[binary_col] = data_clean[binary_col].replace(binary).astype(object)

In [ ]:
val_processed.head()

,usia,jumlah_kontak_kampanye_ini,hari_sejak_kontak_sebelumnya,jumlah_kontak_sebelumnya,tingkat_variasi_pekerjaan,indeks_harga_konsumen,indeks_kepercayaan_konsumen,suku_bunga_euribor_3bln,jumlah_pekerja,pekerjaan_entrepreneur,...,hasil_kampanye_sebelumnya_success,pulau_Jawa,pulau_Kalimantan,pulau_NTB,pulau_NTT,pulau_Papua,pulau_Sulawesi,pulau_Sumatera,pernah_dikontak_sebelumnya,lama_tidak_dikontak
0,-0.370262068560914,-0.586393725964734,0.20653549690576084,-0.3704080748964648,0.9104517988388099,0.6969706760381721,-0.43965915347714307,0.83984749379167,0.8876762547004552,False,...,False,True,False,False,False,False,False,False,-0.4150556876068246,-0.20653695576480327
3,1.1897399896047152,0.20282542483527025,0.20653549690576084,-0.3704080748964648,0.7236019596658266,0.8279798176266605,0.8744627960728713,0.7817319074655721,0.39232917357144653,False,...,False,False,False,False,False,False,False,True,-0.4150556876068246,-0.20653695576480327
4,0.6047392177926043,-0.586393725964734,0.20653549690576084,1.63384834054204,-1.0826131523396791,-1.0699289309119986,-1.1697269032271504,-1.2099964394385652,-0.8346896069071321,False,...,False,False,False,False,False,False,False,True,2.4093152554200956,-0.20653695576480327
6,-0.6627624544669695,-0.586393725964734,0.20653549690576084,-0.3704080748964648,0.9104517988388099,1.639891734576448,-0.25192744639856857,0.7856815104197727,0.8876762547004552,False,...,False,False,False,False,False,True,False,False,-0.4150556876068246,-0.20653695576480327
8,2.1647412759582334,-0.1917841505647319,0.20653549690576084,-0.3704080748964648,-1.0826131523396791,-0.7561965128974296,-1.3574586103057236,-1.1778353868115012,-0.8346896069071321,False,...,False,False,True,False,False,False,False,False,-0.4150556876068246,-0.20653695576480327

In [ ]:
val_processed.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4253 entries, 0 to 5728
Data columns (total 54 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   usia                                   4253 non-null   float64
 1   jumlah_kontak_kampanye_ini             4253 non-null   float64
 2   hari_sejak_kontak_sebelumnya           4253 non-null   float64
 3   jumlah_kontak_sebelumnya               4253 non-null   float64
 4   tingkat_variasi_pekerjaan              4253 non-null   float64
 5   indeks_harga_konsumen                  4253 non-null   float64
 6   indeks_kepercayaan_konsumen            4253 non-null   float64
 7   suku_bunga_euribor_3bln                4253 non-null   float64
 8   jumlah_pekerja                         4253 non-null   float64
 9   pekerjaan_entrepreneur                 4253 non-null   bool
 10  pekerjaan_mahasiswa                    4253 non-null   bool
 11  pekerjaan_manajer                      4253 non-null   bool
 12  pekerjaan_pekerja kasar                4253 non-null   bool
 13  pekerjaan_pemilik bisnis               4253 non-null   bool
 14  pekerjaan_pengangguran                 4253 non-null   bool
 15  pekerjaan_pensiunan                    4253 non-null   bool
 16  pekerjaan_penyedia jasa                4253 non-null   bool
 17  pekerjaan_sosial media specialis       4253 non-null   bool
 18  pekerjaan_teknisi                      4253 non-null   bool
 19  status_perkawinan_lajang               4253 non-null   bool
 20  status_perkawinan_menikah              4253 non-null   bool
 21  pendidikan_Pendidikan Tinggi           4253 non-null   bool
 22  pendidikan_SD                          4253 non-null   bool
 23  pendidikan_SMA                         4253 non-null   bool
 24  pendidikan_SMP                         4253 non-null   bool
 25  pendidikan_TIDAK SEKOLAH               4253 non-null   bool
 26  pendidikan_Tidak Tamat SD              4253 non-null   bool
 27  pinjaman_rumah_1                       4253 non-null   bool
 28  pinjaman_pribadi_1                     4253 non-null   bool
 29  jenis_kontak_telephone                 4253 non-null   bool
 30  bulan_kontak_terakhir_aug              4253 non-null   bool
 31  bulan_kontak_terakhir_dec              4253 non-null   bool
 32  bulan_kontak_terakhir_jul              4253 non-null   bool
 33  bulan_kontak_terakhir_jun              4253 non-null   bool
 34  bulan_kontak_terakhir_mar              4253 non-null   bool
 35  bulan_kontak_terakhir_may              4253 non-null   bool
 36  bulan_kontak_terakhir_nov              4253 non-null   bool
 37  bulan_kontak_terakhir_oct              4253 non-null   bool
 38  bulan_kontak_terakhir_sep              4253 non-null   bool
 39  hari_kontak_terakhir_mon               4253 non-null   bool
 40  hari_kontak_terakhir_thu               4253 non-null   bool
 41  hari_kontak_terakhir_tue               4253 non-null   bool
 42  hari_kontak_terakhir_wed               4253 non-null   bool
 43  hasil_kampanye_sebelumnya_nonexistent  4253 non-null   bool
 44  hasil_kampanye_sebelumnya_success      4253 non-null   bool
 45  pulau_Jawa                             4253 non-null   bool
 46  pulau_Kalimantan                       4253 non-null   bool
 47  pulau_NTB                              4253 non-null   bool
 48  pulau_NTT                              4253 non-null   bool
 49  pulau_Papua                            4253 non-null   bool
 50  pulau_Sulawesi                         4253 non-null   bool
 51  pulau_Sumatera                         4253 non-null   bool
 52  pernah_dikontak_sebelumnya             4253 non-null   float64
 53  lama_tidak_dikontak                    4253 non-null   float64
dtypes: bool(43), float64(11)
memory usage: 577.3 KB

## Modelling Data Training and Data Testing

In [ ]:
X_val = val_processed.reindex(columns=X_train.columns, fill_value=0)

pred_proba = model.predict(X_val)
pred_class = (pred_proba > 0.5).astype(int)
df_result = df_val.loc[val_processed.index].copy()
df_result["prediksi_berlangganan"] = pred_class
df_result["probabilitas"] = pred_proba

df_result.head()

133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

,customer_number,usia,pekerjaan,status_perkawinan,pendidikan,gagal_bayar_sebelumnya,pinjaman_rumah,pinjaman_pribadi,jenis_kontak,bulan_kontak_terakhir,...,jumlah_kontak_sebelumnya,hasil_kampanye_sebelumnya,tingkat_variasi_pekerjaan,indeks_harga_konsumen,indeks_kepercayaan_konsumen,suku_bunga_euribor_3bln,jumlah_pekerja,pulau,prediksi_berlangganan,probabilitas
0,445420,35,penyedia jasa,menikah,SMA,no,yes,yes,cellular,jul,...,0,nonexistent,1.4,93.918,-42.7,4.96,5228.1,Jawa,0,0.06155022978782654
3,816820,51,pengangguran,menikah,Diploma,no,no,no,telephone,may,...,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,Sumatera,0,0.011834412813186646
4,542716,45,teknisi,cerai,SMA,no,yes,no,cellular,may,...,1,failure,-1.8,92.893,-46.2,1.327,5099.1,Sumatera,0,0.06349284946918488
6,434084,32,sosial media specialis,lajang,SMA,no,no,no,telephone,jun,...,0,nonexistent,1.4,94.465,-41.8,4.864,5228.1,Papua,0,0.07615799456834793
8,159684,61,pensiunan,cerai,Pendidikan Tinggi,no,yes,no,cellular,apr,...,0,nonexistent,-1.8,93.075,-47.1,1.384,5099.1,Kalimantan,0,0.25562721490859985